export default {
    port: process.env.PORT || 8085,

    // options for machine learning classifier
    classifier: {
        url: 'http://ubuntu-server:8752/prediction'
    },

    // twitter streaming api options
    twitter: {
        track: [
            'colaboradoresdeltiempo',
            'tiempobrasero',
            'Tiempo_Mercedes',
            'mitiempoen',
            '#eltiempo',
            '@AEMET',
            '#AEMET',
            'sinobas',
            'ecazatormentas',
            'la que esta cayendo nieve',
            'la que esta cayendo lluvia',
            'la que esta cayendo granizo',
            'la que esta cayendo tormenta',
            'la que esta cayendo rayos',
            'nieve cuajando',
            'Meteodemallorca',
            '@NWSSPC',
            'metoffice',
            'manera de llover',
            'manera de nevar',
            'no para de llover',
            'no para de nevar',
            '@eltiempoes',
            'MeteoAlbaceteDR',
            'cumulonimbus tormenta',
            '@SpainStormPred',
            '@spainsevere',
            'banda de precipitacion',
            'frente precipitacion',
            'nevando',
            'nieva',
            'lloviendo',
            'llueve',
            'granizando',
            'tormenta rayos',
            'tormenta relampagos',
            'tormenta truenos',
            'tormenta fuerte',
            'viento fuerte',
            'nublando',
            'meteorologica',
            'picazomario',
            'aemet',
            'aemet avisos',
            'temporal viento',
            'temporal lluvia',
            'temporal nieve',
            'ciclogenesis',
            'instaweather',
            'aguanieve',
            'llueve mucho',
            'aguacero',
            'diluviando',
            'lasextameteo',
            'lluvia intensa',
            'comenzado llover',
            'comenzando llover',
            'comenzado nevar',
            'comenzando nevar',
            'empezado llover',
            'empezando llover',
            'empieza llover',
            'comienza llover',
            'empezado nevar',
            'empezando nevar',
            'empieza nevar',
            'comienza nevar',
            'llover intensidad',
            'nevar intensidad',
            'tormenta aparato electrico',
            'tromba de agua',
            'nubes desarrollo',
            'polar vortex',
            'vortice polar',
            'severa',
            'severe',
            'lluvia',
            'hace viento',
            'nevando',
            'aguacero',
            'nieva',
            'llover',
            'sol',
            'rain',
            'tormenta',
            'frío',
            'sigue',
            '❄',
            'nieve',
            'temporal',
            'calor',
            'agua',
            'radar',
            '°c',
            '☔',
            'warning',
            'polar',
            'weather',
            'cielo',
            'vortex',
            'tornado',
            'paraguas',
            '⚠',
            'km',
            '🌧',
            'info',
            'eléctrica',
            'lluvias',
            'mm',
            'clima',
            'cae',
            'norte',
            'snow',
            'ºc',
            'llueva',
            'proteccion civil',
            'activos',
            'mar',
            'nubes',
            'frio',
            'temperatura',
            'cold',
            'alerta',
            'naranja',
            'temp',
            'aviso',
            'proximos días',
            'alerta',
            'activa',
            'estaciones',
            'según',
            'automáticas',
            'superficie',
            'agencia',
            'meteorología',
            'prevé',
            'temperaturas',
            'temporal',
            'predicción',
            'previsión',
            'fenómenos costeros',
            'riesgo',
            'litros',
            'nevadas',
            '🔔',
            'precipitaciones',
            'probabilidad',
            'viento',
            '⛄',
            'meteorológica',
            'nuboso',
            'máxima',
            'precaución',
            'temperatura',
            'rachas',
            'actualización',
            'información',
            'mínima',
            '°',
            '🌧',
            'cielos',
            'nubosos',
            'posibilidad',
            'nevar',
            'ºc',
            'situación',
            'nubosidad',
            'mínimas',
            'estación',
            'invierno',
            'precipitación',
            'litoral',
            'observatorio',
            'cielo',
            'olas',
            'meteorológico',
            'flooding',
            'inundacion',
            'nevazo'
          ].join(','),
          follow: [
            '89707859',
            '1857150498',
            '310806928',
            '1060403089',
            '1095547530',
            '760166790',
            '767056579745185793',
            '767043893661724672',
            '2544227706',
            '424217382',
            '4038086236',
            '3837113362',
            '2190647784',
            '1588390848',
            '2939588943',
            '1696460815',
            '1190035932',
            '115183451',
            '590060558',
            '1337011070',
            '16117029',
            '427643966',
            '58203491',
            '973903266',
            '567089833',
            '229066643',
            '767056579745185793',
            '87376791',
            '248149823',
            '2238882655',
            '344712910',
            '1076408665',
            '140000155',
            '1196554356',
            '293556004',
            '125396474',
            '270624733',
            '45581271',
            '556410699',
            '2362469894',
            '552223095',
            '3398333033',
            '21706413',
            '798016597',
            '212931502',
            '2864517358',
            '359893504',
            '555711818',
            '249060435',
            '746400355949383680',
            '762974004391112704',
            '1263826782',
            '188685493'
        ].join(',')
    },
};
